project_id = "vdbmhqlogqrxozaibntq"

[functions.config]
verify_jwt = false

[functions.suggestions]
verify_jwt = false

[functions.chat]
verify_jwt = false

[functions.analytics]
verify_jwt = false

[functions.suggested-articles]
verify_jwt = false

[functions.articles]
verify_jwt = false

[functions.project-ai-settings]
verify_jwt = true

[functions.rag-documents]
verify_jwt = true